### ISSUE TITLE
How to execute this project?

### ISSUE THREAD

**Issue by chulphan** [arnaud-deprez/spring-boot-react-sample#2]
Can you let me know how to execute your project??

I tried build frontend and run backend but i faced 404 error.

Thank you.

**Comment by arnaud-deprez** [comment]
Hi @chulphan,

I realized there are other errors and missing parts in the documentation as well.
Let me try to fix it and I'll come back to you after.

**Comment by chulphan** [comment]
This project can be used as RESTAPI Server, but cannot be used serving index.html for SPA.
I did both run frontend and backend, finally running successfully.
Thank you.

**Comment by arnaud-deprez** [comment]
It can @chulphan but you need to build it with `./gradlew clean build -Pprod` and then you can run the jar with `java -jar backend/build/libs/*.jar`

**Comment by chulphan** [comment]
@arnaud-deprez Exactly need to build and run with the jar. But i faced 404 error. 
I think the reason for the error is because index.html(built by frontend) does not exist in the backend/src/main/resources/templates. So the SinglePageApplication is not working correctly....

I want to know how do you think about above.

Thank you

**Comment by arnaud-deprez** [comment]
Did you pass the `-Pprod` option ?

**Comment by arnaud-deprez** [comment]
FYI, I've update the example with Spring Web Reactive stack and React hooks. See #4
